import type { CampaignRecipient } from '@/domain/models/campaign-recipient';
import { CampaignRecipientSchema } from '@/domain/schemas/campaign-recipient.schema';
import { generateId, nowIso } from './utils';

export interface CreateCampaignRecipientInput {
  campaignId: string;
  businessId: string;
  /** Generated by the caller via `lib/campaign/code.ts` — this factory only ever sees the finished code, mirroring `createClaim`'s `tokenHash`. */
  campaignCode: string;
  destinationUrl: string;
  destinationLabel?: string;
}

/** Create a new CampaignRecipient in `'active'` status with zero scan rollups. */
export function createCampaignRecipient(input: CreateCampaignRecipientInput): CampaignRecipient {
  const now = nowIso();

  const record: CampaignRecipient = {
    campaignRecipientId: generateId('recipient_'),
    campaignId: input.campaignId,
    businessId: input.businessId,
    campaignCode: input.campaignCode,
    destinationUrl: input.destinationUrl,
    ...(input.destinationLabel !== undefined && { destinationLabel: input.destinationLabel }),
    status: 'active',
    totalScans: 0,
    estimatedUniqueScans: 0,
    createdAt: now,
    updatedAt: now,
  };

  CampaignRecipientSchema.parse(record);
  return record;
}
