import type { CampaignRecipient } from '@/domain/models/campaign-recipient';
import { CampaignRecipientSchema } from '@/domain/schemas/campaign-recipient.schema';
import { generateId, nowIso } from './utils';

interface CreateCampaignRecipientBase {
  campaignId: string;
  businessId: string;
  /** Generated by the caller via `lib/campaign/code.ts` — this factory only ever sees the finished code, mirroring `createClaim`'s `tokenHash`. */
  campaignCode: string;
}

export type CreateCampaignRecipientInput =
  | (CreateCampaignRecipientBase & {
      /** The default path — resolved at scan time via `claimId`, never a stored URL. `claimId` is absent when the business was already claimed at add-time (see `addCampaignRecipientAction`). */
      destinationType: 'claim';
      claimId?: string;
    })
  | (CreateCampaignRecipientBase & {
      /** The admin-override exception path. */
      destinationType: 'custom';
      destinationUrl: string;
      destinationLabel?: string;
    });

/** Create a new CampaignRecipient in `'active'` status with zero scan rollups. */
export function createCampaignRecipient(input: CreateCampaignRecipientInput): CampaignRecipient {
  const now = nowIso();

  const record: CampaignRecipient = {
    campaignRecipientId: generateId('recipient_'),
    campaignId: input.campaignId,
    businessId: input.businessId,
    campaignCode: input.campaignCode,
    destinationType: input.destinationType,
    ...(input.destinationType === 'claim' && input.claimId !== undefined && { claimId: input.claimId }),
    ...(input.destinationType === 'custom' && {
      destinationUrl: input.destinationUrl,
      ...(input.destinationLabel !== undefined && { destinationLabel: input.destinationLabel }),
    }),
    status: 'active',
    totalScans: 0,
    estimatedUniqueScans: 0,
    createdAt: now,
    updatedAt: now,
  };

  CampaignRecipientSchema.parse(record);
  return record;
}
