import { POSTCARD_BLUE } from './postcard-colors';

export interface PostcardQrWithBadgeProps {
  qrDataUri?: string;
}

/**
 * The recipient's QR code with a small circular Webpresa "W" watermark
 * centered on top of it — a pure CSS/HTML overlay on top of the existing
 * `<img>`, not a change to the QR itself. The underlying PNG (generated by
 * `generateCampaignQrPng`) is untouched, so its scannability is whatever it
 * already was — a logo baked directly into the QR file instead would need
 * a higher error-correction level to stay reliably scannable, which is a
 * separate, later concern if this ever needs to happen at the PNG level
 * rather than as a page overlay (e.g. once Phase 2's Lambda rendering
 * produces the actual print artifact).
 */
export default function PostcardQrWithBadge({ qrDataUri }: PostcardQrWithBadgeProps) {
  return (
    <div
      className="relative flex aspect-square w-full items-center justify-center rounded-md border-[3px] bg-white p-[4%] shadow-[0_4px_10px_rgba(11,30,61,0.18)]"
      style={{ borderColor: POSTCARD_BLUE }}
    >
      {qrDataUri ? (
        // eslint-disable-next-line @next/next/no-img-element
        <img src={qrDataUri} alt="Scan to view your new website" className="h-full w-full" />
      ) : (
        <span className="text-center text-xs text-gray-400">No QR — postcard has no CampaignRecipient</span>
      )}
      {qrDataUri && (
        <span className="absolute flex h-[20%] w-[20%] items-center justify-center rounded-full border-2 bg-white shadow-sm" style={{ borderColor: POSTCARD_BLUE }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/webpresa_w.png" alt="" className="h-[65%] w-[65%] object-contain" />
        </span>
      )}
    </div>
  );
}
